export enum Routes {
  auth = 'Auth',
  main = 'Main',
  mainTabs = 'MainTabs',
  login = 'Login',
  forgotPassword = 'ForgotPassword',
  otp = 'Otp',
  otpSubmit = 'OtpSubmit',
  newPassword = 'NewPassword',
  home = 'Ana səhifə',
  tasks = 'Tapşırıqlar',
  profile = 'Profil',
  profileDetail = 'ProfileDetail',
  notifications = 'Bildirişlər',
  reports = 'Hesabatlar',
  newReport = 'YeniHesabat',
  terminals = 'Terminallar',
  terminalDetails = 'TerminalEtrafli',
  detailedReport = 'HesabatEtrafli',
  taskProcess = 'TaskProcess',
  pinSetup = 'PinSetup',
  onboarding = 'OnBoarding',
  currentTask = 'currentTask',
}
